### ISSUE TITLE
Request for use of source code in www.umeh.top (澳大选咩课)

### ISSUE THREAD

**Issue by BoxMars** [kchomacau/timetable#1]
我們是 www.umeh.top 的開發者,我們希望將閣下的 _**課程表模擬助手 Timetable Simulator**_ 項目與之集成. 我們希望獲得閣下的授權, 以在我們的服務中使用本項目的原始代碼.如果您希望保留對衍生項目的著作權, 我們也誠邀閣下加入我們的開發團隊.

**Comment by kchomacau** [comment]
你好，幸會。在標註代碼片段原創者為 K. C. Ho 的情況下，歡迎使用本項目之代碼。請一同努力造福澳大學弟學妹們吧！ -Kc

**Comment by BoxMars** [comment]
我們還希望您能加入 UMHelper ， 考慮到本項目後續迭代時可能會遇到問題，以便及時與您取得聯繫。
